name: Deploy Backend to HuggingFace Spaces

on:
  push:
    branches: [main]
    paths: [server/**]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Push to HuggingFace Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_SPACE: ${{ secrets.HF_SPACE_NAME }}
        run: |
          git config --global user.email "ci@github.com"
          git config --global user.name "GitHub Actions"
          git subtree push --prefix=server \
            https://ilyas:${HF_TOKEN}@huggingface.co/spaces/${HF_SPACE} main
